### ISSUE TITLE
Question: PyPI and setuptools_scm

### ISSUE THREAD

**Issue by MathMagique** [pypa/python-packaging-user-guide#308]
Many projects use `setuptools_scm` to extract the version number from source control. During development, i.e., between version tags, the version number for such a project is

    {next_version}.dev{distance}+{scm letter}{revision hash}

(see the [setuptools_scm readme](https://github.com/pypa/setuptools_scm)). My question is:

_Is it acceptable for projects to upload development versions of Python packages to PyPI?_

This would enable project users to test unstable versions conveniently and could lead to quicker feedback for the projects, e.g., to check whether a patch has really resolved an end user problem or whether a new feature provides a sufficiently refined user experience. The downside is that this would put greater strain on PyPI due to the increased volume of releases.

Is that something you can recommend as a best practice, or something you would advice against?

**Comment by jonparrott** [comment]
@MathMagique PEP 440 has provisions for [development release](https://www.python.org/dev/peps/pep-0440/#developmental-releases) versions. As such, PyPI is fine if you want to do development releases.

I probably wouldn't do a development release for every single commit to master, but you should be fine to cut development releases.

**Comment by MathMagique** [comment]
@jonparrott Thanks a lot for the quick and clear answer.

**Comment by dstufft** [comment]
One quick clarification, PyPI will *not* let you upload versions that have a ``+`` in them, preferring instead to reserve that namespace for "local" modifications. Some projects (like setuptools_scm) also use that to store more specific version about what VCS revision a release was cut from, however those versions cannot be uploaded to PyPI.

As @jonparrott noted, it is perfectly fine to otherwise release development releases to PyPI using the ``.dev``,  (or alpha, beta, rc, etc) version signifiers.

**Comment by MathMagique** [comment]
@dstufft Thank you for the clarification!
