### ISSUE TITLE
Make linkchecker warning-only.

### ISSUE THREAD

**Issue by jonparrott** [pypa/python-packaging-user-guide#341]

**Comment by ncoghlan** [comment]
Just a heads up that I just broke the linkchecking again in order to push https://github.com/pypa/python-packaging-user-guide/pull/347 out ASAP :)

**Comment by jonparrott** [comment]
I'll make it just a warning once I get back from vacation later next week.
:)

**Comment by ddbeck** [comment]
I was about to start another issue on this but decided this is more of an escalation of this one. Now that I've had my own first run in with the link checker in #345, I think it's sufficiently confusing that we should turn it off (in failure or warning mode) until there's a clearly documented path to adding or fixing links.

The contributor docs need to cover:

1. What to do if there's a broken link
1. What to do if there's a new heading (and why this matters because it's not clear to me why it should)
1. How to install and run the link checker locally

And then link to this section of the contributing docs, should the link check fail.

I knew that the link checker existed and I had a vague idea of what it did from reading the earlier PR. I still couldn't figure it out. Before giving up, I tried a bunch of things like running the described command, upgrading from the requirements files in the repo, guessing at running `pip install nox`, pointlessly googling "nox", and running `ag nox` which turned up nothing because of course the one mention in the repo is in a hidden file.

Until there's a clearly marked path for handling the link checker, I think broken links are preferable to making contributors figure this out.

**Comment by jonparrott** [comment]
Totally in agreement, I'm just out of office - I'll grab this first thing
when I get back - likely this coming Friday. :)
