### ISSUE TITLE
Migrating to PyPI.org page has incorrect instructions.

### ISSUE THREAD

**Issue by rec** [pypa/python-packaging-user-guide#346]
Apparently as of yesterday there's a new way to push things to PyPI, leading the developer to this page https://packaging.python.org/guides/migrating-to-pypi-org/  

But this page has issues.

First, there's this statement:

    Tools that support PyPI.org by default are twine v1.8.0+ (recommended tool), setuptools 27+, or the distutils included with Python 3.4.6+, Python 3.5.3+, Python 3.6+, and 2.7.13+.

But the [Python versions page](https://www.python.org/doc/versions/) doesn't _have_ a 3.4.6!  Indeed, for MacOS, the most recent version is 3.4.4.

It's not at all clear how to use twine to replicate my existing functionality, and I have no wish to learn a new package today.  It's not clear how I could use setuptools 27 from within Python 3.4.4.

Continuing in the document, it says:

    If for some reason you’re unable to upgrade the version of your tool to a version that defaults to using PyPI.org, then you may edit ~/.pypirc and include the repository: line, but use the value https://upload.pypi.org/legacy/ instead.

    If you use TestPyPI, you must update your ~/.pypirc to handle TestPyPI’s new location, by replacing https://testpypi.python.org/pypi with https://test.pypi.org/legacy/.

These instructions do not work on this machine, running MacOS 10.9.5:

    $ python setup.py register -r pypitest
    running register
    running egg_info
    writing Expressy.egg-info/PKG-INFO
    writing dependency_links to Expressy.egg-info/dependency_links.txt
    writing top-level names to Expressy.egg-info/top_level.txt
    reading manifest file 'Expressy.egg-info/SOURCES.txt'
    writing manifest file 'Expressy.egg-info/SOURCES.txt'
    running check
    Registering Expressy to https://test.pypi.org/legacy/
    Server response (410): This API is no longer supported, instead simply upload the file.

Overall, changing things with no apparent warning so that a common part of many developers' workflow suddenly breaks is negatively indicated.  

A task I thought would take me five minutes has consumed 30, with no clear resolution in sight.

**Comment by ncoghlan** [comment]
Hi @rec, the new upload service doesn't require (or even support) pre-registration, so skipping the register step should resolve your immediate issue.

This is a definite omission from the migration guide though, so I've filed a PR to add a new section to that covering the changes to how package registration works: https://github.com/pypa/python-packaging-user-guide/pull/347

As far as the lack of reach of our current methods of pre-announcing API changes goes, we agree we have a problem in that regard, but it's part of a more general problem with a lack of standard mechanisms for issuing PSF Infrastructure related announcements, which is currently being discussed over at https://github.com/python/psf-infra-meta/issues/1

As far as *why* the new server doesn't emulate the old registration API, it's because we wanted to make initial releases simpler (by eliminating the pre-registration step), while also leaving room for possible future addition of a dedicated name reservation feature. https://github.com/pypa/warehouse/issues/1627 has more discussion of that point.

**Comment by ncoghlan** [comment]
Closed via #346, which added a new subsection to the service migration guide: https://packaging.python.org/guides/migrating-to-pypi-org/#registering-package-names-metadata

**Comment by rec** [comment]
Thanks!

**Comment by rec** [comment]
So I spake too soon.  The push worked fine for pypitest - but now I get a error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> for pypi itself, even if I use Python 3.6.

This documentation bug is probably not the best place to seek help for this - any better ideas?  Sorry to make this pop up again.

**Comment by ncoghlan** [comment]
@rec Would you mind filing that one at https://github.com/pypa/packaging-problems/issues ?

It would also be useful to know if the certificate validation problem is specific to the upload client, or if you also have problems getting to the domain via a web browser or tools like curl and wget.
