### ISSUE TITLE
Complete minimal example for Metadata file format version 1.2

### ISSUE THREAD

**Issue by techtonik** [pypa/python-packaging-user-guide#350]
At https://packaging.python.org/specifications/ there is no overview about minimal required set of fields for metadata 1.2 file format. An example `PKG-INFO` would make many issues more clear.

**Comment by jonparrott** [comment]
Who would know this information? @dstufft @ncoghlan?

**Comment by ncoghlan** [comment]
@techtonik Note that you are still unwelcome as a participant in any project I am involved in. There is no reset button on that just because the PyPA repositories don't automatically track the PSF's blanket ban on your participation in PSF provided communication channels.

The details on which fields are optional and which are required is contained in PEP 345, which is referenced from the specifications page: https://www.python.org/dev/peps/pep-0345/#fields

https://github.com/pypa/python-packaging-user-guide/issues/319 and https://github.com/pypa/pypa.io/issues/11 cover the fact that we want to change the architecture of the specifications page to migrate the reference content out of the PEPs that originally defined it and into the User Guide.
