### ISSUE TITLE
extras_require not documented in distributing-packages.rst

### ISSUE THREAD

**Issue by zmwangx** [pypa/python-packaging-user-guide#368]
`extras_require` is documented at [setuptools.readthedocs.io]( https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) but not in `distributing-packages.rst`.

**Comment by jonparrott** [comment]
This is intentional, as the distributing package tutorial is pretty minimal. I want to address this when I write the new tutorials (#203 et al), I just haven't quite found time.

In the meantime, I could see a separate guide on this.

Closing for now. If you want to see a specific guide we'd need to figure out what to stick in it.

**Comment by zmwangx** [comment]
Thanks for the explanation. I don't really need a specific guide — I just had trouble remembering the name `extras_require` yesterday, went to the guide, and realized it's not there. If it doesn't belong there in the first place, no big deal.
