### ISSUE TITLE
Packaging docs don't make it clear is README.rst included automatically

### ISSUE THREAD

**Issue by pekkaklarck** [pypa/python-packaging-user-guide#377]
Packaging docs [recommend using README.rst](https://packaging.python.org/tutorials/distributing-packages/#readme-rst) but docs don't make it clear is it included in distributions automatically or not. The docs under the MANIFEST.in section refer to [distutils documentation](https://docs.python.org/3.4/distutils/sourcedist.html#specifying-the-files-to-distribute) which says that README.txt or README is included but doesn't mention about README.rst.

If I remember correctly, distutils didn't actually include README.rst earlier and it needed to be listed in MANIFEST.in. Now it seems to be included when I'm testing with Python 3.6, but I'm not sure can I count on it nor would it work also with earlier versions.

I also noticed that packaging docs refer to Python 3.4 docs about distutils instead of the latest docs. I checked that 3.6 docs don't tell anything about README.rst either, though.

**Comment by gtback** [comment]
I don't know if I count as a first timer since I already submitted one PR (#408), but I'd be happy to take this on. 

Looking through the history of distutils, it looks like it's support for README.rst is [new in Python 3.7](https://github.com/python/cpython/commit/f9f87f0934ca570293ba7194bed3448a7f9bf39c), but setuptools has supported README.rst since [at least five years ago](https://github.com/pypa/setuptools/commit/cafaa3bd07185df0c17a19edee8820494d34267c). Though the Guide seems to strongly recommend setuptools over distutils, it may still be worth explaining the distinction when it comes to README.rst. 

Setuptools seems to also support README.md, but distutils does not.

**Comment by jonparrott** [comment]
Go for it, @gtback!
