### ISSUE TITLE
Account for Jupyter shell/kernel interactions

### ISSUE THREAD

**Issue by ncoghlan** [pypa/python-packaging-user-guide#407]
The tutorials now mention `!python -m pip ...` as a way of running installation commands.

However, this isn't quite right due to the problems @jakevdp describes in https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/index.html

At the very least, we should update those examples to use the variant of the command that ensures the right environment is being updated.

**Comment by pgadige** [comment]
I'm working on this issue. 
As I understand, we should provide the variant of the commands of the form `!python -m pip ...` that will work inside a Jupyter notebook right?

**Comment by pgadige** [comment]
May I know how you'd like this change to be incorporated in the tutorial?

I suppose there's only one tutorial, i.e. [Installing Packages](https://packaging.python.org/tutorials/installing-packages/) that mentions Jupyter notebook's enhanced shell. Perhaps, I've missed others. I'll appreciate your help in identifying those.

I have an idea. I think instead of updating each `!python -m pip ...` installation command, we could add a note to highlight the variant of the installation command as it ought to be used in a Jupyter notebook.

A rough **draft** of note: 
If you're installing or upgrading a python package, say, `<package>` in the Jupyter notebook, you can run the command -
`import sys
!{sys.executable} -m pip install <package>`  or 
`import sys
!{sys.executable} -m pip upgrade <package>`

since there are sections describing different approaches to install packages using `pip` in the tutorial, I think adding a generic note would look good instead of adding the variant for each command.

I'll appreciate your thoughts on this.

**Comment by ncoghlan** [comment]
Sorry, my original description was rather vague, and I had to go re-read the tutorial myself to work out what I meant :)

The problem is specifically with the first note in https://packaging.python.org/tutorials/installing-packages/#ensure-you-can-run-python-from-the-command-line, where we mention `!python --version` at the end as an example of running Python from the Jupyter shell.

That isn't right for the reasons Jake gives in his post (i.e. the running Jupyter kernel may not corresponding to the `python` executable on `PATH`). 

We haven't introduced `python -m pip install` at that point, so I'd suggest sticking with `!{sys.executable} --version` as the example command, but also break those two paragraphs out into their own note (rather than having them be tacked on to the end of the previous note).
