### ISSUE TITLE
add a FAQ

### ISSUE THREAD

**Issue by qwcode** [pypa/python-packaging-user-guide#49]
in addition to the tutorial, I think a FAQ would be another way to help users find the information they need.

**Comment by souravsingh** [comment]
What will be need to add in the FAQs?

**Comment by ncoghlan** [comment]
An FAQ can be a good way to tackle questions where the answers aren't obvious (often for historical reasons), but even *raising* the question (let alone trying to answer it) would confuse newcomers rather than helping them.

A number of the existing "Advanced Topics" are actually detailed answers to FAQs (e.g. wheel vs egg, pip vs easy_install), so it might be possible to seed an FAQ with those questions, giving a short version of the answer, with a link to the more detailed answer in the Advanced topics section.

**Comment by theacodes** [comment]
I'm going to close this - the packaging guide more or less acts as one big FAQ at this point. I think if there are common questions that aren't being answered, we should address those with tutorials or guides.
