### ISSUE TITLE
Pipfile status question

### ISSUE THREAD

**Issue by cs01** [pypa/python-packaging-user-guide#497]
[This question](https://www.reddit.com/r/Python/comments/8jd6aq/why_is_pipenv_the_recommended_packaging_tool_by/dz0kxlh/) was posed on reddit, and I have the same question. What is the PyPA's take on this?

> The problem with Pipfile and pipfile.lock is that their status is unclear (at least, to me). On the one hand, they are not officially standardized. On the other hand, they are used by an officially recommended packaging tool. So, should we consider this format to be the new standard or not? Also, what should developers of alternative packaging tools do? Should they aim at supporting Pipfile and pipfile.lock? Or should they invent their own format as well?

Also any insight into whether it's planned to be merged into the standardized [pyproject.toml](https://www.python.org/dev/peps/pep-0518/) would be appreciated.

Thank you!

**Comment by dstufft** [comment]
Generally the idea behind ``Pipfile`` was that it wasn't a standard, because it wasn't a cross tool file in the same way that ``pyproject.toml``, wheels, etc was. It was intended to be specific to pip so it didn't make sense to send it through the standardization process.

Maybe that is wrong and we should send it through standardization. Merging it into ``pyproject.toml`` isn't currently planned but it's maybe possible? Would require a faira mount of discussion because they're generally targeting different enough use cases that combining them might end up being more confusing than having them separate.

**Comment by cs01** [comment]
Thanks!
