### ISSUE TITLE
Warning in managing-dependencies/#installing-packages-for-your-project links to "open" Github issue that is closed

### ISSUE THREAD

**Issue by FunkyLoveCow** [pypa/python-packaging-user-guide#500]
The warning at the bottom of the [managing-dependencies/#installing-packages-for-your-project](https://packaging.python.org/tutorials/managing-dependencies/#installing-packages-for-your-project) section reads:

> Warning
> Due to an open issue with pipenv, it’s not currently reliable to use pipenv to create environments for different Python versions (as environment marker conditions may not be processed correctly). The interpreter version you use in your project should be the same as the interpreter version used to install pipenv. When testing against multiple versions with tox, install pipenv into each test environment, as described here. 

It links to https://github.com/pypa/pipenv/issues/857 which was closed in March 2018. 

Should this warning be removed or tutorial updated to reflect the outcome of the above issue?

**Comment by theacodes** [comment]
@dstufft WDYT?

**Comment by theacodes** [comment]
or @ncoghlan.

**Comment by ncoghlan** [comment]
There's an existing issue for fixing the caveat at https://github.com/pypa/python-packaging-user-guide/issues/452

It arguably isn't quite as simple as just deleting it, although doing that would likely be better than keeping it around (since it's irrelevant to anyone running the latest version of pipenv).
