### ISSUE TITLE
How to build packages with c / c++ code

### ISSUE THREAD

**Issue by JonasGroeger** [pypa/python-packaging-user-guide#53]
I would like to write something about it like I [already did here](https://github.com/cython/cython/wiki/64BitCythonExtensionsOnWindows).

Where should I put it in the hierarchy?

**Comment by nchammas** [comment]
@JonasGroeger - FYI, your first link is broken.

**Comment by nchammas** [comment]
I'm interested in helping the [dask/hdfs3](https://github.com/dask/hdfs3/) project improve their packaging so that users don't need to separately install a C++ dependency before installing their Python wrapper.

https://github.com/dask/hdfs3/issues/113

I believe the relevant section in the Packaging Guide is [this one on publishing binary extensions](https://packaging.python.org/extensions/#publishing-binary-extensions), but it's incomplete.

Can anyone chime in either here or on https://github.com/dask/hdfs3/issues/113 with some pointers on whether what we want to do is possible? I'd be happy to polish those pointers into a PR against the guide.

**Comment by theacodes** [comment]
@JonasGroeger if you're still interested in doing this, it would make a wonderful guide. Let me know if it's still something you want to take on!

**Comment by theacodes** [comment]
No worries. I will close this for now.
