### ISSUE TITLE
Remove references to pipenv

### ISSUE THREAD

**Issue by 9034725985** [pypa/python-packaging-user-guide#589]
I just learned that Pipenv is no longer an official project. 
I request we remove references to it from the page 
https://packaging.python.org/guides/tool-recommendations/
This issue is a part of work that reverses #437 and clarifies that pipenv is not an official project. 

It can't even go about the simple process of: 

1. `pipenv install` 
2. `pipenv uninstall --all-dev` 

without giving an error.
See 
https://github.com/pypa/pipenv/issues/3469
to track this issue.

**Comment by Conan-Kudo** [comment]
It's an official project of PyPA still, it's just not being pushed as the "be-all-end-all" option.

**Comment by theacodes** [comment]
Hi, Pipenv is still a project managed by PyPA members and lives under the PyPA org. As far as I'm aware, this status has not changed.

The only requirement for a project to join the PyPA is that its maintainers agree to our Code of Conduct. Additionally, it isn't a requirement that a project be part of the PyPA to be a part of this documentation or part of the tool recommendations, it just has to be in common usage and follow the patterns and expectations (loose consensus) of the disutils-sig mailing list and packaging working group.

I'm going to close this issue, but please let me know if you have any other questions.

**Comment by ncoghlan** [comment]
Note that the referenced pipenv bug report was actually a Fedora downstream packaging bug (there was an error in the switch from bundled dependencies to shared dependencies)

**Comment by mstrofbass** [comment]
While complete removal of references to pipenv may be unnecessary, given the clear dysfunction in the pipenv project (see: https://github.com/pypa/pipenv/issues/4058), it should be features less prominently in the documentation. With it being set out as it is on the tool recommendations page, most people will simply opt for it instead of exploring the others, completely unaware of how dysfunctional it is. 

At the very least, the documentation should not say to "[u]se Pipenv to manage library dependencies when developing Python applications." It should either simply provide a list of options with no description (bad) or a list of options with descriptions that indicate the differences and use cases (good). Simply saying to use something else if pipenv does not meet one's needs as a recommendation is silly - most of the people won't know whether it meets their needs until they use it and waste time figuring out it doesn't.

Although we can't get rid of the inherent bias in an ordered list, we can reduce the prominence of the reference to pipenv so that people will be less assuming.

**Comment by hartwork** [comment]
@theacodes please consider re-opening. 69c412726da3419ef45f392ec19d14848d87c22c did not fix that pipenv is the primary recommendation.
